//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define PERMISSION_SERVICE              1
#define PERMISSION_INVENTORY            2
#define ID_MOTIFY_STAFF                 3
#define ID_CANCEL_RETREAT               3
#define PERMISSION_PERSONNEL            3
#define ID_CANCEL_STAFF                 4
#define PERMISSION_MANAGER              4
#define IDD_LOGIN                       101
#define IDI_ICONLOGIN                   102
#define IDR_PERSONNEL                   103
#define IDD_STAFF_EDIT                  104
#define IDD_ORDER                       106
#define IDD_RETREAT                     107
#define IDD_CHANGE_TABLE                108
#define IDD_CUSTOM_CHECKOUT             109
#define IDD_START_TABLE                 111
#define IDD_CHANGE_PASSWD               112
#define IDD_TAB_PASSWD                  112
#define IDD_DIALOG1                     113
#define IDD_SYS_MANAGEMENT              113
#define IDD_TAB_CHILD2                  114
#define IDD_TAB_FINANCE                 114
#define IDD_TAB_CHILD1                  115
#define IDD_TAB_USER                    115
#define IDD_EDIT_USER                   116
#define IDD_CONSUMPTION_DETAIL          117
#define IDD_TAB_PERSONNEL               118
#define IDD_TAB_SERVER                  119
#define IDD_BASIC_COMMODITY             120
#define IDD_EDIT_COMMODITY              121
#define IDD_EDIT_COMMODITY_CATEGORY     122
#define IDD_EDIT_PERMISSION             123
#define IDD_TAB_BASIC_INFO_             124
#define IDD_TAB_BASIC_INFO              124
#define IDD_BASIC_TABLE                 125
#define IDD_BASIC_UNTENSIL              126
#define IDC_USERNAME                    1000
#define IDC_PASSWORD                    1001
#define ID_ADD_STAFF                    1001
#define ID_DELETE_STAFF                 1002
#define IDC_STAFF_ID                    1003
#define IDC_STAFF_NAME                  1004
#define IDC_STAFF_AGE                   1005
#define IDC_STAFF_SALARY                1006
#define IDC_STAFF_DEPT                  1007
#define IDC_STAFF_EMAIL                 1008
#define IDC_STAFF_PHONE                 1009
#define IDC_STAFF_ADDRESS               1010
#define IDC_SEX_MAN                     1011
#define IDC_SEX_WOMAN                   1012
#define IDC_STAFF_DEPT2                 1013
#define IDC_ADD_DISH                    1018
#define IDC_DELETE_DISH                 1019
#define IDC_SAVE_MENU                   1020
#define IDC_CANCEL_MENU                 1021
#define IDC_CUSTOM_MENU                 1022
#define IDC_TABLE_NUM                   1024
#define IDC_CUSTOM_NUM                  1025
#define IDC_TABLE_RETREAT_NUM           1026
#define IDC_CUSTOM_RETREAT_NUM          1027
#define IDC_CUSTOM_MENU_RETREAT         1029
#define ID_DELETE_RETREAT               1030
#define ID_SAVE_RETREAT                 1031
#define IDC_TABLE_NUM_OLD               1034
#define IDC_PAYABLE_NUM_OLD             1035
#define IDC_REAL_NUM_OLD                1036
#define IDC_TABLE_TIME_OLD              1037
#define IDC_TABLE_NUM_NEW               1039
#define IDC_PAYABLE_NUM_NEW             1040
#define IDC_REAL_NUM_NEW                1041
#define IDC_TABLE_TIME_NEW              1042
#define IDC_FLOOR_NUM_AVAILABLE         1045
#define IDC_FLOOR                       1045
#define IDC_SAVE_CHANGE                 1046
#define IDC_CANCLE_CHANGE               1047
#define IDC_TABLE_NUM_CHECKOUT          1047
#define IDC_CUSTOM_NUM_CHECKOUT         1048
#define IDC_MENU_CHEKOUT                1049
#define IDC_RECEIVALBE_CHECKOUT         1050
#define IDC_PAIDIN_CHECKOUT             1051
#define IDC_GIVECHANGE_CHECKOUT         1052
#define IDC_SAVE_CHECKOUT               1053
#define IDC_CANCEL_CHECKOUT             1054
#define ID_START_OK                     1054
#define ID_START_CANCEL                 1055
#define IDC_REAL_NUM_START              1058
#define IDC_CUSTOMER_NO_START2          1059
#define IDC_CUSTOMER_NO_START           1059
#define IDC_BUTTON1                     1063
#define IDC_ADD_TABLE                   1063
#define IDC_CONSUMPTION_DETAIL          1063
#define ID_SERVICE_START                1063
#define IDC_BASIC_INFO_ADD              1063
#define IDC_COMMODITY_CANCEL            1063
#define IDC_E_PERMISSION_ADD            1063
#define IDC_B_FLOOR                     1063
#define IDC_B_UTENSIL_ADD               1063
#define IDC_BUTTON2                     1064
#define IDC_DELETE_TABLE                1064
#define ID_SERVICE_CHANGE               1064
#define IDC_BASIC_INFO_MODIFY           1064
#define IDC_QUERY_DETAIL                1064
#define IDC_E_PERMISSION_MODIFY         1064
#define IDC_PERMISSION_ADD              1064
#define IDC_B_ROOM                      1064
#define IDC_B_UTENSIL_MODIFY            1064
#define IDC_COMBO1                      1065
#define IDC_DELETE_USER                 1065
#define ID_SERVICE_ORDER                1065
#define IDC_BASIC_INFO_DELETE           1065
#define IDC_E_PERMISSION_DELETE         1065
#define IDC_B_TABLE                     1065
#define IDC_B_UTENSIL_DELETE            1065
#define IDC_CHOICE_DAY                  1066
#define ID_SERVICE_CHECKOUT             1066
#define IDC_BASIC_EDIT_CATEGORY         1066
#define IDC_DELETE_PERMISSION           1066
#define IDC_E_PERMISSION_CANCEL         1066
#define IDC_EDIT_PERMISSION             1066
#define IDC_B_UTENSIL_SORT              1066
#define ID_SERVICE_BOOK                 1067
#define IDC_TABLE_AVAILABLE             1070
#define IDC_LIST3                       1071
#define IDC_START_TABLE                 1071
#define IDC_LIST5                       1073
#define IDC_CUSTOMER_TABLE              1073
#define IDC_DISH_NUMBER                 1074
#define IDC_REPAST_MENU                 1075
#define IDC_STATE_ORDER                 1076
#define IDC_OLD_PASSWD                  1077
#define IDC_NEW_PASSWD                  1078
#define IDC_CONFIRM                     1079
#define IDC_TAB1                        1079
#define IDC_TAB_MAIN                    1079
#define IDC_CHILD_TAB                   1079
#define IDC_USER_LIST                   1080
#define IDC_ADD_USER                    1081
#define IDC_MODIFY_USER                 1082
#define IDC_                            1083
#define IDC_CONSUMPTION                 1083
#define IDC_E_END_TIME                  1083
#define IDC_CHOICE_YEAR                 1084
#define IDC_CHOICE_DATE                 1085
#define IDC_YEAR                        1086
#define IDC_MONTH                       1087
#define IDC_DAY                         1088
#define IDC_CHOICE_MONTH                1090
#define IDC_USER_NAME                   1094
#define IDC_USER_PASSWD                 1095
#define IDC_USER_PASSWD2                1096
#define IDC_SYS_MANAGEMENT              1097
#define IDC_USER_NAME2                  1097
#define IDC_PERSONNEL_MANAGEMENT        1098
#define IDC_USER_PERMISSION             1098
#define IDC_STOCK_MANAGEMENT            1099
#define IDC_USER_NAME3                  1099
#define IDC_DESK_MANAGEMENT             1100
#define IDC_E_ADD_USER                  1101
#define IDC_E_MODIFY_USER               1102
#define IDC_E_DELETE_USER               1103
#define IDC_E_CANCEL                    1104
#define IDC_E_USER_NAME                 1105
#define IDC_E_STAFF_NAME1               1105
#define IDC_E_STAFF_NAME                1105
#define IDC_E_USER_PASSWD               1106
#define IDC_E_CONFROM_PASSWD            1107
#define IDC_E_USER_NAME2                1108
#define IDC_E_LOGIN_NAME                1108
#define IDC_LIST1                       1110
#define IDC_EDIT1                       1111
#define IDC_EDIT2                       1112
#define IDC_EDIT3                       1113
#define IDC_EDIT4                       1114
#define ID_PERSONNEL_QUERY              1117
#define IDC_S_ID                        1119
#define ID_PERSONNEL_STAFF_ID           1120
#define ID_PERSONNEL_DEPT               1121
#define ID_PERSONNEL_STAFF_NAME         1122
#define ID_PERSONNEL_SEX                1123
#define ID_MAN                          1124
#define ID_WOMAN                        1125
#define ID_PERSONNEL_NAME               1126
#define ID_PERSONNEL_DEPT_COMBO         1127
#define ID_PERSONNEL_INFO               1128
#define ID_PERSONNEL_STAFF_SUM          1129
#define ID_PERSONNEL_DEPT_SUM           1130
#define ID_SERVICE_REFRESH              1130
#define ID_CURRENT_RECORD_SUM           1131
#define ID_G_TABLE_INFO                 1131
#define ID_S_FLOOR_INFO                 1132
#define ID_SERVICE_COMBO                1133
#define ID_SERVICE_LIST                 1134
#define IDC_S_DESK_ORDER                1135
#define IDC_S_BASIC_INFO                1136
#define IDC_BASIC_INFO                  1137
#define IDC_S_BASIC_INFO_OPERATE        1140
#define IDC_TREE_COMMODITY              1141
#define IDC_CHECKOUT_TABLE_NO           1142
#define IDC_E_S_COMMODITY               1143
#define IDC_MENU_TREE                   1144
#define IDC_E_S_COMMODITY_ID            1146
#define IDC_E_S_COMMODITY_NAME          1147
#define IDC_E_COMMODITY_NAME            1148
#define IDC_E_S_COMMODITY_PURCHASE      1149
#define IDC_E_S_COMMODITY_SUM           1150
#define IDC_E_S_COMMODITY_CATEGORY      1151
#define IDC_E_S_COMMODITY_UNIT          1152
#define IDC_E_S_COMMODITY_SALE          1154
#define IDC_E_COMMODITY_ID              1155
#define IDC_E_COMMODITY_PURCHASE        1156
#define IDC_E_COMMODITY_SUM             1157
#define IDC_E_COMMODITY_CATEGORY        1158
#define IDC_E_COMMODITY_UNIT            1159
#define IDC_E_COMMODITY_SALE            1160
#define IDC_CATEGORY_DELETE             1167
#define IDC_CATEGORY_ADD                1168
#define IDC_CATEGORY_CANCEL             1169
#define IDC_S_COMMODITY_CATEGORY        1170
#define IDC_S_CATEGORY_NAME             1171
#define IDC_S_CATEGORY_ID               1172
#define IDC_E_CATEGORY_ID               1173
#define IDC_E_CATEGORY_NAME             1174
#define IDC_CATEGORY_MODIFY             1175
#define IDC_START_DATE                  1176
#define IDC_END_DATE                    1177
#define IDC_E_START_TIME                1177
#define IDC_E_USER_ID                   1178
#define IDC_E_USER_PERMISSION           1179
#define IDC_S_PERMISSION                1180
#define IDC_S_PERMISSION_NO             1181
#define IDC_S_PERMISSION_NAME           1182
#define IDC_E_PERMISSION_NO             1183
#define IDC_E_PERMISSION_NAME           1184
#define IDC_T_TABLE_INFO                1184
#define IDC_S_TABLE_INFO                1185
#define IDC_L_TABLE_INFO                1186
#define IDC_T_UTENSIL                   1187
#define IDC_S_UTENSIL                   1188
#define IDC_L_UTENSIL                   1189
#define IDR_ADD                         40001
#define IDR_DELETE                      40002
#define IDR_MODIFY                      40003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        127
#define _APS_NEXT_COMMAND_VALUE         40004
#define _APS_NEXT_CONTROL_VALUE         1190
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
